# Generated by Django 4.0.5 on 2022-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_Prodcart',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='17:32:19'),
        ),
    ]
