# Generated by Django 4.0.5 on 2022-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_order_id_prodcart_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='17:37:49'),
        ),
    ]
