# Generated by Django 4.0.5 on 2022-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_date_alter_order_time_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='id_prod',
        ),
        migrations.AddField(
            model_name='keywords',
            name='id_cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='17:19:50'),
        ),
    ]
