# Generated by Django 4.0.5 on 2022-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_keywords_id_prod_keywords_id_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='18:24:09'),
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
