# Generated by Django 4.0.5 on 2022-08-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_time_delete_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cust',
            new_name='id_cust',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 21)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='11:49:11'),
        ),
    ]
