# Generated by Django 4.0.5 on 2022-08-21 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_productcart_id_order_alter_order_deliverydate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='id_order',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='id_prod',
        ),
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 14, 53, 36, 932490)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='14:53:36'),
        ),
    ]
