# Generated by Django 4.0.5 on 2022-08-21 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_productcart_id_prod_alter_order_deliverydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='id_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 14, 59, 10, 756677)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='14:59:10'),
        ),
    ]
