# Generated by Django 4.0.5 on 2022-08-21 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_productcart_id_order_alter_order_deliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 15, 0, 16, 226146)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='15:00:16'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='id_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
