# Generated by Django 4.0.5 on 2022-08-21 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_order_deliverydate_alter_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 17, 21, 35, 48557)),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_cust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='17:21:35'),
        ),
    ]
