# Generated by Django 4.0.5 on 2022-08-21 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_order_deliverydate_alter_order_id_cust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 17, 22, 25, 452119)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='17:22:25'),
        ),
    ]
