# Generated by Django 4.0.5 on 2022-08-21 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_order_deliverydate_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 19, 25, 18, 521692)),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='19:25:18'),
        ),
    ]
